### ISSUE TITLE
read only to database

### ISSUE THREAD

**Issue by klemenkobetic** [galaxyproject/ansible-postgresql-objects#1]
is it possible to add read only user rights to database?

**Comment by natefoo** [comment]
@klemenkobetic Sure:

``` yaml
postgresql_objects_privileges:
  - database: foo_db
    roles: bar_user
    objs: ALL_IN_SCHEMA
    privs: SELECT
```

**Comment by klemenkobetic** [comment]
hm, what i did for now :

``` yaml
postgresql_objects_databases:
  - name: database1
    owner: dbuser
postgresql_objects_users:
  - name: dbuser
    password: mypass1
  - name: dbreaduser
    password: mypass2
```

It's ok that dbuser, as owner, can do everything.

But with this settings, dbreaduser can also do everything.

I presume, something is set default and I should override, any idea? :)

**Comment by natefoo** [comment]
Unless you default permissions allow `dbreaduser` access to databases owned by other users, it should not have read access let alone full privileges. This should do what you want:

``` yaml
postgresql_objects_databases:
  - name: database1
    owner: dbuser
postgresql_objects_users:
  - name: dbuser
    password: mypass1
  - name: dbreaduser
    password: mypass2
postgresql_objects_privileges:
  - database: database1
    roles: dbreaduser
    objs: ALL_IN_SCHEMA
    privs: SELECT
```
